id: 
name: GitOps.PullRequestIssueManagement
description: GitOps.PullRequestIssueManagement primitive
owner: 
resource: repository
disabled: false
where: 
configuration:
  resourceManagementConfiguration:
    scheduledSearches:
    - description: 
      frequencies:
      - hourly:
          hour: 6
      filters:
      - isIssue
      - isOpen
      - hasLabel:
          label: 'Needs: author feedback'
      - hasLabel:
          label: 'Status: no recent activity'
      - noActivitySince:
          days: 3
      actions:
      - closeIssue
    - description: 
      frequencies:
      - hourly:
          hour: 6
      filters:
      - isIssue
      - isOpen
      - hasLabel:
          label: 'Needs: author feedback'
      - noActivitySince:
          days: 4
      - isNotLabeledWith:
          label: 'Status: no recent activity'
      actions:
      - addLabel:
          label: 'Status: no recent activity'
      - addReply:
          reply: This issue has been automatically marked as stale because it has been marked as requiring author feedback but has not had any activity for **4 days**. It will be closed if no further activity occurs **within 3 days of this comment**.
    - description: 
      frequencies:
      - hourly:
          hour: 6
      filters:
      - isIssue
      - isOpen
      - hasLabel:
          label: duplicate
      - noActivitySince:
          days: 1
      actions:
      - addReply:
          reply: This issue has been marked as duplicate and has not had any activity for **1 day**. It will be closed for housekeeping purposes.
      - closeIssue
    eventResponderTasks:
    - if:
      - payloadType: Issue_Comment
      - isAction:
          action: Created
      - isActivitySender:
          issueAuthor: True
      - hasLabel:
          label: 'Needs: author feedback'
      - isOpen
      then:
      - addLabel:
          label: 'Needs: attention :wave:'
      - removeLabel:
          label: 'Needs: author feedback'
      description: 
    - if:
      - payloadType: Issues
      - not:
          isAction:
            action: Closed
      - hasLabel:
          label: 'Status: no recent activity'
      then:
      - removeLabel:
          label: 'Status: no recent activity'
      description: 
    - if:
      - payloadType: Issue_Comment
      - hasLabel:
          label: 'Status: no recent activity'
      then:
      - removeLabel:
          label: 'Status: no recent activity'
      description: 
    - if:
      - payloadType: Pull_Request
      then:
      - inPrLabel:
          label: 'Status: In PR'
      description: 
    - if:
      - payloadType: Issue_Comment
      - commentContains:
          pattern: '#please-close'
          isRegex: False
      then:
      - closeIssue
      description: 
    - if:
      - payloadType: Issues
      - isAction:
          action: Opened
      - and:
        - bodyContains:
            pattern: javascript
            isRegex: False
        - or:
          - bodyContains:
              pattern: typescript
              isRegex: False
      then:
      - assignTo:
          users:
          - diberry
      - addLabel:
          label: javascript
      - assignTo:
          users:
          - diberry
      description: 
    - if:
      - payloadType: Issues
      - isAction:
          action: Opened
      - bodyContains:
          pattern: /java/
          isRegex: False
      then:
      - addLabel:
          label: java
      - assignTo:
          users:
          - karlerickson
      description: 
    - if:
      - payloadType: Issues
      - isAction:
          action: Opened
      - bodyContains:
          pattern: /python/
          isRegex: False
      then:
      - addLabel:
          label: python
      - assignTo: {}
      description: 
    - if:
      - payloadType: Issues
      - isAction:
          action: Opened
      - bodyContains:
          pattern: /ansible/
          isRegex: False
      then:
      - addLabel:
          label: ansible
      - assignTo:
          users:
          - 'TomArcherMsft '
      description: 
    - if:
      - payloadType: Issues
      - isAction:
          action: Opened
      - bodyContains:
          pattern: /chef/
          isRegex: False
      then:
      - addLabel:
          label: chef
      - assignTo:
          users:
          - 'TomArcherMsft '
      description: 
    - if:
      - payloadType: Issues
      - isAction:
          action: Opened
      - titleContains:
          pattern: /jenkins/
          isRegex: False
      then:
      - addLabel:
          label: jenkins
      - assignTo:
          users:
          - TomArcherMsft
      description: 
    - if:
      - payloadType: Issues
      - isAction:
          action: Opened
      - bodyContains:
          pattern: /terraform/
          isRegex: False
      then:
      - addLabel:
          label: terraform
      - assignTo:
          users:
          - TomArcherMsft
      description: 
    - if:
      - payloadType: Issues
      - isAction:
          action: Opened
      - bodyContains:
          pattern: /azure-cli/
          isRegex: False
      then:
      - addLabel:
          label: azure-cli
      - assignTo:
          users:
          - 'dbradish-microsoft '
      description: 
onFailure: 
onSuccess: 
